baseurl: /
title: Earth Lab
languageCode: en-us
paginate: '10'
theme: Mainroad
disqusShortname: ''
googleAnalytics: ''
Author:
  avatar: img/avatar2.png
  bio: A true Earth Data Scientist 
  name: Mussa Ngosha
Params:
  authorbox: yes
  description: 
  logo: 
    subtitle: Machine Learning for Earth obervation and big data ANALYTICS
  opengraph: yes
  pager: yes
  post_meta:
    - date
    - categories
  readmore: yes
  sidebar:  
    home: right
    list: right
    single: right
    widgets:
      - search
      - recent
      - categories
      - taglist
  twitter_cards: no
  widgets:
    recent_num: 5
    tags_counter: no
